# Generated by Django 4.1.5 on 2023-02-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
    ]
