# Generated by Django 4.1.5 on 2023-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_remove_sales_pizza_remove_sales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
